#!/usr/bin/perl -w
use strict;
use warnings;
use Garden::CGIHandler;
use Garden::Assessment;

my $query = Garden::CGIHandler->new;

my $assessment = Garden::Assessment->new(request => $query->request, 'decode-content'=>0);
my $response = $assessment->modify_assessment;
$query->send_response($response);
