#!/usr/bin/perl -w
use strict;
use warnings;
use Garden::CGIHandler;
use Garden::Assessment;

my $query = Garden::CGIHandler->new;

my $assessment = Garden::Assessment->new(request => $query->request);
my $response = $assessment->add_assessment_question;
$query->send_response($response);
