#!/usr/bin/perl -w
use strict;
use warnings;
use Garden::CGIHandler;
use Garden::Group;

my $query = Garden::CGIHandler->new;

my $group = Garden::Group->new(request => $query->request, 'decode-content'=>0);
my $response = $group->modify_group;
$query->send_response($response);
