#!/usr/bin/perl -w
use strict;
use warnings;
use Garden::CGIHandler;
use Garden::User;

my $query = Garden::CGIHandler->new;

my $user = Garden::User->new(request => $query->request);
my $response = $user->update_password;
$query->send_response($response);
